apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentprocessingmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ComponentProcessingMicroservice
  template:
    metadata:
      labels:
        app: ComponentProcessingMicroservice
    spec:
      containers:
      - name: componentprocessingmicroservice
        image: returnorder.azurecr.io/componentmicroservice:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: componentsn

---
apiVersion: v1
kind: Service
metadata:
  name: componentprocessingmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ComponentProcessingMicroservice
